Задание 5.2 - найти определитель

In [1]:
import numpy as np
a=np.array([[1,2,3],[4,0,6],[7,8,9]],float)
np.linalg.det(a)

59.999999999999986

Задание 5.5 - Найти смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [2]:
b=np.array([[1,5,0],[2,8,7],[7,1.5,3]],float)
np.linalg.det(b)

228.50000000000009

Задание 5.3 -Вычислите матрицу, обратную данной в задании 5.2:

In [3]:
np.linalg.inv(a)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

5.1 Вычислите: (5Е)–1, где Е – единичная матрица размера 5х5.

In [4]:
c=np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]],float)
print(c)
c=5*c
print(c)
print(np.linalg.det(c))
np.linalg.inv(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
3124.999999999999


array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

Приведите пример матрицы 4х4, ранг которой равен 1.

In [5]:
d=np.array([[1,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],float)
print(d)
print(np.linalg.matrix_rank(d))

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1
